Bump RuboCop to 0.77.0
RuboCop 0.77.0 has been released.
https://github.com/rubocop-hq/rubocop/releases/tag/v0.77.0

This PR updates the following changes.

```console
% bin/rake rubocop
bin/rubocop --parallel
Error: The `Layout/AlignArray` cop has been renamed to
`Layout/ArrayAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/AlignParameters` cop has been renamed to
`Layout/ParameterAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentAssignment` cop has been renamed to
`Layout/AssignmentIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentFirstArgument` cop has been renamed to
`Layout/FirstArgumentIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentFirstArrayElement` cop has been renamed to
`Layout/FirstArrayElementIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentFirstHashElement` cop has been renamed to
`Layout/FirstHashElementIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/LeadingBlankLines` cop has been renamed to
`Layout/LeadingEmptyLines`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/TrailingBlankLines` cop has been renamed to
`Layout/TrailingEmptyLines`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/DuplicatedKey` cop has been renamed to
`Lint/DuplicateHashKey`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/MultipleCompare` cop has been renamed to
`Lint/MultipleComparison`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/StringConversionInInterpolation` cop has been renamed to
`Lint/RedundantStringCoercion`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Naming/UncommunicativeBlockParamName` cop has been renamed to
`Naming/BlockParameterName`.
(obsolete configuration found in .rubocop.yml, please update it)
rake aborted!
Command failed with status (2): [bin/rubocop --parallel...]
/Users/koic/src/github.com/bundler/bundler/Rakefile:123:in `block in
<top (required)>'
/Users/koic/src/github.com/bundler/bundler/Rakefile:15:in `block in
invoke'
/Users/koic/src/github.com/bundler/bundler/Rakefile:14:in `invoke'
/Users/koic/src/github.com/bundler/bundler/spec/support/rubygems_ext.rb:87:in
`load'
/Users/koic/src/github.com/bundler/bundler/spec/support/rubygems_ext.rb:87:in
`gem_load_and_activate'
/Users/koic/src/github.com/bundler/bundler/spec/support/rubygems_ext.rb:45:in
`gem_load'
Tasks: TOP => rubocop
(See full trace by running task with --trace)
```

And this PR has auto-correction of .rubocop.yml using Mry gem.
https://github.com/pocke/mry

```console
% gem i mry
Fetching mry-0.77.0.2.gem
Successfully installed mry-0.77.0.2
1 gem installed
% mry .rubocop.yml
```